### ISSUE TITLE
'ResultName' column is generated inconsistently

### ISSUE THREAD

**Issue by AsbjornJC** [opentap/Parquet#40]
## Issue:
The column 'ResultName' is only generated when there is multiple steps in a test plan e.g., when a test plan contains a charge and sineresult step.

When a testplan only contains a single step e.g., a charge or sineresult step then the 'ResultName' column does not exist in the generated parquet file.

### Environment:
Tested in KS8500 UI DEV environment

### Parquet version:
0.2.0

### Artifacts from the executed Test plans with readmes:
[DiverseTests.zip](https://github.com/opentap/Parquet/files/14065840/DiverseTests.zip)

#### Note:
ResultViewerWeb should be able to rely on the 'ResultName' column; however, this is not possible currently.

**Comment by frederikja163** [comment]
Could not reproduce this, also i dont think you are using the latest version of the result listener as you dont have the resultname column in any of the files you uploaded. Maybe try updating your runner version in KS8500 and see if that fixes the issue.
