### ISSUE TITLE
Merging files

### ISSUE THREAD

**Issue by frederikja163** [opentap/Parquet#5]
Could allow for 3 methods of file merging.

 - No merging
 - Forced one file per result
 - Forced one file per plan

**Comment by db-ks** [comment]
@AsgerIversen How many files would you expect for a TestPlanRun?

I am inclined to go for `1` file per TestPlanRun. But we can also go with `1` file per result source.

**Comment by frederikja163** [comment]
Theres pros and cons of going either way. In the end i think this will be controlled by a macro string. Ie the name you give to the result file. See #2
