### ISSUE TITLE
An error occurs when running test step with Parquet

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/Parquet#7]
**Environment:**

Windows 10, 64-bit
Test Automation 9.22.0-rc.3

**Steps to reproduce:**

1. Install Parquet package
2. Set Parquet as result listener
3. Add a Sine test step
4. Run the Test Plan

**Actual result:**

An error occurs - FileNotFoundException: Could not load file or assembly 'Parquet, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de28deb604dd91c9' or one of its dependencies. The system cannot find the file specified.

Log: [Latest.txt](https://github.com/opentap/Parquet/files/12818458/Latest.txt)

![image](https://github.com/opentap/Parquet/assets/118886454/a64fb3c0-895c-4699-bc77-6e959c863f30)

**Comment by Razvan-Muresan** [comment]
Verified on KS8400 version 9.22.0-rc.4
